# site settings
title: wx blog
SEOtitle: 吴翔的博客
#header-img:
email: 18428368840@163.com
description: 这是一个有趣的博客
keyword: "java"
url: "https:/wxme.github.io"
theme: jekyll-theme-minimal

# sitebar settings
sidebar: true
sidebar-about-description: "导航栏"
#sidebar-avatar:头像

# SNS settings:社交账号
RSS: false
weibo_username:     wxme
zhihu_username:     wxme
github_username:    wxme
facebook_username:  wxme
jianshu_username:   jianshu_id